"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var router = (0, express_1.Router)();
var authForWebSocket_1 = require("../../controllers/users/authForWebSocket");
var changePassword_1 = require("../../controllers/users/changePassword");
var createUser_1 = require("../../controllers/users/createUser");
var forgotPassword_1 = require("../../controllers/users/forgotPassword");
var forgotPassword3_1 = require("../../controllers/users/forgotPassword3");
var login_1 = require("../../controllers/users/login");
var logout_1 = require("../../controllers/users/logout");
var get_1 = require("../../controllers/users/profile/get");
var getEventsLimitedInfo_1 = require("../../controllers/users/profile/getEventsLimitedInfo");
var getVenuesLimitedInfo_1 = require("../../controllers/users/profile/getVenuesLimitedInfo");
var searchEvents_1 = require("../../controllers/users/profile/searchEvents");
var searchVenues_1 = require("../../controllers/users/profile/searchVenues");
var update_1 = require("../../controllers/users/profile/update");
var updateImg_1 = require("../../controllers/users/profile/updateImg");
var protect_1 = __importDefault(require("../../middleware/auth/protect"));
var forgotPassword2_1 = require("../../controllers/users/forgotPassword2");
router.post("/", createUser_1.createUser);
router.post("/login", login_1.login);
router.get("/logout", logout_1.logout);
router.post("/change-password", protect_1.default, changePassword_1.changePassword);
router.post("/forgot-password-1st-step", forgotPassword_1.forgotPassword1stStep);
router.post("/forgot-password-2nd-step", forgotPassword2_1.forgotPassword2ndStep);
router.post("/forgot-password-3rd-step", forgotPassword3_1.forgotPassword3rdStep);
router.get("/getProfile", get_1.getProfile);
router.patch("/updateProfile", protect_1.default, update_1.updateProfile);
router.get("/getLimitedInfoProfile", getEventsLimitedInfo_1.getLimitedInfoProfile);
router.patch("/updateImg", protect_1.default, updateImg_1.updateImg);
router.get("/searchEvent", searchEvents_1.searchEvent);
router.get("/getLimitedVenuesInfoProfile", getVenuesLimitedInfo_1.getLimitedVenuesInfoProfile);
router.get("/searchVenues", searchVenues_1.searchVenues);
router.get("/authWorker", authForWebSocket_1.authenticateUser);
exports.default = router;
//# sourceMappingURL=users.js.map