"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var checkIsAdmin_1 = require("../../controllers/admin/checkIsAdmin");
var adminList_1 = require("../../controllers/users/adminList");
var deleteUser_1 = require("../../controllers/users/admin/deleteUser");
var eventList_1 = require("../../controllers/users/admin/eventList");
var deleteEvent_1 = require("../../controllers/users/admin/deleteEvent");
var venueList_1 = require("../../controllers/users/admin/venueList");
var deleteVenue_1 = require("../../controllers/users/admin/deleteVenue");
var eventServiceList_1 = require("../../controllers/users/admin/eventServiceList");
var deleteEventServices_1 = require("../../controllers/users/admin/deleteEventServices");
var storiesList_1 = require("../../controllers/users/admin/storiesList");
var deleteStories_1 = require("../../controllers/users/admin/deleteStories");
var shortVidsList_1 = require("../../controllers/users/admin/shortVidsList");
var deleteShortVid_1 = require("../../controllers/users/admin/deleteShortVid");
var groupsList_1 = require("../../controllers/users/admin/groupsList");
var deleteGroup_1 = require("../../controllers/users/admin/deleteGroup");
var reviewsList_1 = require("../../controllers/users/admin/reviewsList");
var groupPostList_1 = require("../../controllers/users/admin/groupPostList");
var deleteGroupPost_1 = require("../../controllers/users/admin/deleteGroupPost");
var groupPostCommentList_1 = require("../../controllers/users/admin/groupPostCommentList");
var deleteGroupPostComment_1 = require("../../controllers/users/admin/deleteGroupPostComment");
var verifyService_1 = require("../../controllers/users/admin/verifyService");
var unVerify_1 = require("../../controllers/users/admin/unVerify");
var eventBlacklist_1 = require("../../controllers/users/admin/eventBlacklist");
var addAdvert_1 = require("../../controllers/users/admin/addAdvert");
var getAdvert_1 = require("../../controllers/users/getAdvert");
var deleteAdvert_1 = require("../../controllers/users/admin/deleteAdvert");
var router = (0, express_1.Router)();
router.get("/", checkIsAdmin_1.checkIsAdmin);
router.get("/adminList", adminList_1.adminList);
router.delete("/deleteUser/:user_id", deleteUser_1.deleteUser);
router.get("/eventList", eventList_1.eventList);
router.delete("/deleteEvent/:event_id", deleteEvent_1.deleteEvent);
router.get("/venueList", venueList_1.venueList);
router.delete("/deleteVenue/:venue_id", deleteVenue_1.deleteVenue);
router.get("/eventServiceList", eventServiceList_1.eventServiceList);
router.delete("/deleteEventServices/:event_services_id", deleteEventServices_1.deleteEventServices);
router.get("/storiesList", storiesList_1.storiesList);
router.delete("/deleteStory/:story_id", deleteStories_1.deleteStory);
router.get("/shortVidsList", shortVidsList_1.shortVidList);
router.delete("/deleteShortVid/:short_vid_id", deleteShortVid_1.deleteShortVid);
router.get("/groupList", groupsList_1.groupsList);
router.delete("/deleteGroup/:group_id", deleteGroup_1.deleteGroup);
router.get("/reviewList", reviewsList_1.reviewsList);
router.get("/groupPostList", groupPostList_1.groupPostList);
router.delete("/deleteGroupPost/:group_post_id", deleteGroupPost_1.deleteGroupPost);
router.get("/groupPostCommentList", groupPostCommentList_1.groupPostCommentList);
router.delete("/deleteGroupPostComment/:group_post_comment_id", deleteGroupPostComment_1.deleteGroupPostComment);
router.get("/verifyEventService/:event_services_id", verifyService_1.verifyEventService);
router.get("/unVerifyEventService/:event_services_id", unVerify_1.unVerifyEventService);
router.get("/blackListEvent/:event_id/:action", eventBlacklist_1.blackListEvent);
router.post("/addAdvert", addAdvert_1.addAdvert);
router.get("/getAdverts", getAdvert_1.getAdvert);
router.delete("/deleteAd/:ad_id", deleteAdvert_1.deleteAdvert);
exports.default = router;
//# sourceMappingURL=admin.js.map